server:
  port: 8000
spring:
  application:
    name: tecsmile.top.service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tecsmile?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Admin@123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 176500
      maximum-pool-size: 15
    type: com.zaxxer.hikari.HikariDataSource
# MySQL数据库配置
#spring.datasource.url: jdbc:mysql://47.98.161.153:3306/tecsmile?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#spring.datasource.username: root
#spring.datasource.password: Admin@123
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.type:
#指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
#spring.datasource.testWhileIdle: true
# 指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个.
#spring.datasource.testOnBorrow: true
#指明是否在归还到池中前进行检验
#spring.datasource.testOnReturn: false
#spring.datasource.timeBetweenEvictionRunsMillis: 600000
#连接在池中保持空闲而不被空闲连接回收器线程(如果有)回收的最小时间值，单位毫秒. 设置7小时
#spring.datasource.minEvictableIdleTimeMillis: 25200000
#maxActive: 最大活动连接: 连接池在同一时间能够分配的最大活动连接的数量,如果设置为非正数则表示不限制
#spring.datasource.primary.maxActive: 500
#spring.datasource.dbcp2.max-idle: 100



# pagehelper
#pagehelper.helperDialect: mysql
#pagehelper.page-size-zero: false
#pagehelper.offset-as-page-num: false
#pagehelper.row-bounds-with-count: true
#pagehelper.reasonable: true
#pagehelper.supportMethodsArguments: true
#pagehelper.params: count=countSql

#stop springboot trigger commons-dbcp2 close exception, disable JMX in springboot
spring.jmx.enabled: false

logging.level.com.tecsmile.top.mapper: DEBUG

# 防止关联查询是List查询为空报异常
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

#mybatis
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #mapper-locations: classpath:/mapper/**Mapper.xml
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tecsmile.top.pojo
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
   # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug